// components/cards/BuyPointsCard.jsx
"use client";

import React from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faCheckCircle, faBrain } from "@fortawesome/free-solid-svg-icons"; // Added faBrain
import {
	Dialog,
	DialogContent,
	DialogDescription,
	DialogHeader,
	DialogTitle,
	DialogTrigger,
	DialogClose,
	DialogFooter,
} from "@/components/ui/dialog";
import { useState } from "react";
import { BeatLoader } from "react-spinners";
import { useRouter } from "next/navigation";
import { Button as ShadButton } from "@/components/ui/button"; // Assuming you use shadcn/ui Button

export default function BuyPointsCard({ packageId, price, points, email, name, lifespan, userId }) {
	const [submitError, setSubmitError] = useState(null);
	const [loading, setLoading] = useState(false);
	const router = useRouter();

	async function submit() {
		setLoading(true);
        setSubmitError(null);

		const orderPayload = {
			type: "points", // This tells your API it's a points package purchase
			price: price,
			// email: email, // API can get email from session if needed for notification, or keep it for direct use
			userId: userId, // User ID for whom the order is being created
			
            // Points being purchased
			editingPoints: points.editingPoints || 0,
			designPoints: points.designPoints || 0,
			recordingPoints: points.recordingPoints || 0,
            consultingPoints: points.consultingPoints || 0, // <<< ADDED

			lifespan: lifespan,
			status: "Чака плащане", // More appropriate initial status
            package_definition_id: packageId, // Optional: if you want to link to the original package
            // Description will be auto-generated by the API for points orders
		};

		try {
			const response = await fetch("/api/createOrder", {
				method: "POST",
				headers: { "Content-Type": "application/json" },
				body: JSON.stringify(orderPayload),
			});

			const result = await response.json(); // Always try to parse

			if (!response.ok) {
				setSubmitError(result.message || "Грешка при регистриране на поръчка.");
				setLoading(false);
				return;
			}

            // Successfully created order
			router.push(`/thankyou?orderId=${result.order?.id || ''}&type=pointsPurchase`); // Redirect to thank you page

			// Your commented-out email sending logic can go here or be handled by the API
            // For now, we assume success and redirect.

		} catch (err) {
			console.error("Submit order catch error:", err);
			setSubmitError("Грешка при комуникация със сървъра. Моля опитайте по-късно.");
		} finally {
            setLoading(false); // Ensure loading is always set to false
        }
	}

	return (
		<Dialog>
			<DialogContent
				className="bg-background border-secondary text-foreground shadow-xl rounded-lg"
				onCloseAutoFocus={(e) => e.preventDefault()}
			>
				<DialogHeader>
					<DialogTitle className="text-lg font-semibold text-gray-200">
						Потвърждение на Поръчка
					</DialogTitle>
					<DialogDescription className="pt-3 text-sm text-gray-400">
						Моля, прегледайте детайлите на вашия пакет преди да потвърдите.
					</DialogDescription>
				</DialogHeader>
                <div className="py-4 space-y-3">
                    <p className="text-xl font-bold text-center text-white">
                        Цена: <span className="text-accent">{price} лв.</span>
                    </p>
                    <div className="text-sm text-gray-300 space-y-1 bg-gray-700/50 p-3 rounded-md border border-gray-600">
                        {points.editingPoints > 0 && <p>Видео монтаж: <span className="font-semibold text-white">{points.editingPoints}</span> т.</p>}
                        {points.recordingPoints > 0 && <p>Видео заснемане: <span className="font-semibold text-white">{points.recordingPoints}</span> т.</p>}
                        {points.designPoints > 0 && <p>Дизайн: <span className="font-semibold text-white">{points.designPoints}</span> т.</p>}
                        {points.consultingPoints > 0 && <p>Консултации: <span className="font-semibold text-white">{points.consultingPoints}</span> т.</p>} {/* <<< ADDED */}
                        <p>Валидност на пакета: <span className="font-semibold text-white">{lifespan}</span> дни</p>
                    </div>
                </div>

				{submitError && <p className="text-red-400 text-xs text-center py-2">{submitError}</p>}

				<DialogFooter className="sm:justify-end gap-2 pt-4">
					<DialogClose asChild>
						<ShadButton variant="outline" className="border-gray-600 text-gray-300 hover:bg-gray-700">Назад</ShadButton>
					</DialogClose>
					<ShadButton
						onClick={submit}
						disabled={loading}
						className="bg-accent hover:bg-accentLighter text-white"
					>
						{loading ? <BeatLoader color="#fff" size={8} /> : "Поръчай Сега"}
					</ShadButton>
				</DialogFooter>
			</DialogContent>

            {/* Card Display */}
            <div className="rounded-2xl min-h-[16rem] w-full border border-secondary overflow-hidden bg-background/80 backdrop-blur-md shadow-xl flex flex-col hover:shadow-accent/30 transition-shadow duration-300">
				<div className="p-6 border-b border-secondary bg-transparent text-center">
					<p className="text-4xl font-[800] bg-gradient-to-b from-white to-gray-300 bg-clip-text text-transparent">
						{price} лв.
					</p>
				</div>

				<div className="p-6 flex flex-col flex-grow">
					<div className="space-y-2.5 mb-6 flex-grow">
						{points.editingPoints > 0 && (
                            <p className="font-medium text-sm text-gray-200 flex items-center gap-2.5">
                                <FontAwesomeIcon className="text-accentLighter w-4 h-4" icon={faCheckCircle}/>
                                Видео монтаж - {points.editingPoints} т.
                            </p>
                        )}
						{points.recordingPoints > 0 && (
                            <p className="font-medium text-sm text-gray-200 flex items-center gap-2.5">
                                <FontAwesomeIcon className="text-accentLighter w-4 h-4" icon={faCheckCircle}/>
                                Видео заснемане - {points.recordingPoints} т.
                            </p>
                        )}
						{points.designPoints > 0 && (
                            <p className="font-medium text-sm text-gray-200 flex items-center gap-2.5">
                                <FontAwesomeIcon className="text-accentLighter w-4 h-4" icon={faCheckCircle}/>
                                Дизайн - {points.designPoints} т.
                            </p>
                        )}
                        {points.consultingPoints > 0 && ( // <<< ADDED
                            <p className="font-medium text-sm text-gray-200 flex items-center gap-2.5">
                                <FontAwesomeIcon className="text-accentLighter w-4 h-4" icon={faBrain}/>
                                Консултации - {points.consultingPoints} т.
                            </p>
                        )}
					</div>

					<p className="font-medium text-xs text-gray-400 flex items-center gap-2 mt-auto pt-2 border-t border-gray-700/50">
						<FontAwesomeIcon className="text-accentLighter w-3.5 h-3.5" icon={faCheckCircle} />
						Валидност: {lifespan} дни
					</p>

					<DialogTrigger asChild className="w-full mt-5">
						<ShadButton variant="default" className="bg-accent hover:bg-accentLighter text-white font-semibold h-10 text-sm shadow-lg">
                            Поръчай Този Пакет
                        </ShadButton>
					</DialogTrigger>
				</div>
			</div>
		</Dialog>
	);
}